### ISSUE TITLE
Error on require

### ISSUE THREAD

**Issue by FSpierckel** [ideacreation/react-native-barcodescanner#1]
Hello,

when I require the library, I have an error : 

'BarcodeScannerView' has no propType for native prop 'RNBarcodeScannerView.scaleX' of native type 'number'.

Have you an issue to solve this problem ?

Thanks in advance,
Florian

**Comment by andreaskeller** [comment]
Hi,

I have just fixed it and uploaded a new release (0.1.2) to npm.
Thanks to @dsibiski who had fixed the issue already in the rnplay fork.

Andreas

**Comment by dsibiski** [comment]
@andreaskeller I had intended to send you a PR with the fix and forgot about it, sorry about that! Great lib btw, the RNPlay Android app is in content review right now and should be available shortly. :smile:

**Comment by andreaskeller** [comment]
@dsibiski glad to hear you like it. you guys are doing amazing work with the react native playground! just checked the android app out. nice!
