### ISSUE TITLE
can i use this module for ios

### ISSUE THREAD

**Issue by shaikhussian** [ideacreation/react-native-barcodescanner#13]
hai,this repo was very helpful to me, but i have doubt that is there any possibility to use the same module in ios, if possible please tell me that how to do it

**Comment by shaikhussian** [comment]
please respond

**Comment by andreaskeller** [comment]
hi, no at the moment the module is only for android. for ios you can use https://github.com/lwansbrough/react-native-camera which is also able to scan barcodes.
