### ISSUE TITLE
does not scan barcode.

### ISSUE THREAD

**Issue by john1jan** [ideacreation/react-native-barcodescanner#14]
This module, is working for QRCODE, but it is not able to scan Barcode

**Comment by john1jan** [comment]
scan you test scanning this barcode
![image](https://cloud.githubusercontent.com/assets/4264813/14430670/2e1e0740-0020-11e6-9d85-1e3a277c6ec7.png)

**Comment by andreyvital** [comment]
@john1jan 

This library/module is only a wrapper around https://github.com/dm77/barcodescanner ─ so I think this issue doesn't belongs to here. Do you agree?

Maybe you can report it there.

**Comment by john1jan** [comment]
I think there is some issue in ReactNative rendering. The same view works fine in Native Side. The camera preview is also very clear. 

I used the same ZXingScannerView in a Native Activity and tested. It works great. But when the same view is used in React Native UI component it is blurring and not scanning barcodes.

Submitted a issue on this in react github repo, start commenting on it 

https://github.com/facebook/react-native/issues/6930

**Comment by andreaskeller** [comment]
Hi,

The component should be able to scan the following barcode formats:

BarcodeFormat.PARTIAL
BarcodeFormat.EAN8
BarcodeFormat.UPCE
BarcodeFormat.ISBN10
BarcodeFormat.UPCA
BarcodeFormat.EAN13
BarcodeFormat.ISBN13
BarcodeFormat.I25
BarcodeFormat.DATABAR
BarcodeFormat.DATABAR_EXP
BarcodeFormat.CODABAR
BarcodeFormat.CODE39
BarcodeFormat.PDF417
BarcodeFormat.QRCODE
BarcodeFormat.CODE93
BarcodeFormat.CODE128

I never had an issue with blurring of the camera preview. Can you please provide a small project on github to reproduce the error? Also which react native version do you use?

**Comment by john1jan** [comment]
It is working fine in full screen. The actual issue was, the BarcodeScannerView should be in full screen, I was displaying the BarcodeScannerView in half of the screen. So the Scanner view was getting distorted.
But issue is still present in BarcodeScannerView when you reduce the height of the view.

I have made workaround, like this, Made the BarcodeScannerView fullscreen and placed my other view components on top of BarcodeScannerView.

**Comment by andreaskeller** [comment]
Glad you found a workaround. I think I can close the issue then.
