### ISSUE TITLE
Orientation and size of view finder

### ISSUE THREAD

**Issue by sahilaug** [ideacreation/react-native-barcodescanner#32]
I noticed that QR code is easily read in portrait but bar code is read easily in landscape orientation. Is this the known behaviour or am I doing something wrong ?
Second question is apart from the viewFinderBackgroundColor, viewFinderBorderColor, viewFinderBorderWidth, viewFinderBorderLength, viewFinderShowLoadingIndicator given in the README, can I edit any other styling of the view finder like height, width etc. ?

**Comment by ddzyndra** [comment]
I have the same issue. @sahilaug Did you manage to resolve this issue ?

**Comment by andreaskeller** [comment]
@sahilaug orientation bug is fixed with the newest version.

`viewFinderHeight` and `viewFinderWidth` exist as well. You could also provide your own custom viewfinder with `showViewFinder={false}` and your viewfinder as a child of the barcode scanner component.
