### ISSUE TITLE
when scan EAN_* barcode is  not read

### ISSUE THREAD

**Issue by geniepapa** [ideacreation/react-native-barcodescanner#33]

**Comment by chujian** [comment]
Indeed

**Comment by xinggg22** [comment]
I have the same problem ,  I think is because of  remove uses "https://github.com/dm77/barcodescanner". Only use ZXing , scan barcode is so slow than Zbar!

**Comment by ThaJay** [comment]
this help? https://github.com/ideacreation/react-native-barcodescanner/issues/37#issuecomment-231708733

**Comment by andreaskeller** [comment]
@geniepapa @chujian @xinggg22 after the rewrite you could only scan 1D barcodes in landscape mode. That's fixed now with the newest version.
