### ISSUE TITLE
no camera image in viewfinder on react-native 0.29

### ISSUE THREAD

**Issue by ThaJay** [ideacreation/react-native-barcodescanner#39]
It all worked on react-native 0.28
Just upgraded to 0.29 and the viewfinder is gone. If I set a absolute width / height and all I see is a red outline.

**Comment by ackdav** [comment]
check your version with 'react-native-barcodescanner' with npm list... sounds like the same issue i just closed

**Comment by ThaJay** [comment]
```
$ npm list grep react-native-barcodescanner
appname@0.0.1 /home/dev/app
└── react-native-barcodescanner@3.0.0 
```

**Comment by ackdav** [comment]
ok.. what is the remote debugger saying?

**Comment by ThaJay** [comment]
no errors.
I encountered this when looking into your issue. Went back to rn 28 to be able to continue my work.

**Comment by matb33** [comment]
The instructions need to be updated... The part that tells you to add new BarcodeScannerPackage() to MainActivity.java should instead go in MainApplication.java (with the relevant import statement)

**Comment by ThaJay** [comment]
okay thanks. :)
What do we need to have rnpm pick up on this? or do they have to update?

**Comment by aakashsigdel** [comment]
I am having this issue on 0.28. npm list shows react-native-barcodescanner@3.0.0

When I do viewFinderShowLoadingIndicator={true}, it gives me a warning ProgressBarAndroid is deprecated and keeps showing the progress bar and the view finder doesn't load.

**Comment by andreaskeller** [comment]
@ThaJay @matb33 I updated the instructions for react-native 0.29. With react-native 0.29.2 `react-native link` (`rnpm`) works with `MainApplication.java`.

**Comment by andreaskeller** [comment]
@aakashsigdel version 3.1.1 uses `ActivityIndicator` instead of `ProgressBarAndroid`.
