### ISSUE TITLE
pop to the Previous scene in android 4.x black scene in screen

### ISSUE THREAD

**Issue by Cocoon-break** [ideacreation/react-native-barcodescanner#47]
use component in the scene,and I pop it .some thing happened.
![a](https://cloud.githubusercontent.com/assets/6791439/17392309/000b3916-5a4f-11e6-93b4-751d5dba71ea.png)

**Comment by ncnlinh** [comment]
I just had the same issue.

**Comment by ncnlinh** [comment]
Apparently it only happens if I use InteractionManager to render a placeholder (to finish the navigation animation) before the actual scanner is rendered

**Comment by liuyimx** [comment]
@Cocoon-break 我也遇到此问题，现在你是如何解决的？

**Comment by liuyimx** [comment]
@ncnlinh  it's not work for me, i remove all 'InteractionManager' use.

**Comment by h2oiswater** [comment]
黑屏啊 黑屏啊 太烦了

**Comment by h2oiswater** [comment]
@Cocoon-break 解决了吗？

**Comment by michalkow** [comment]
I have the same problem. I do not use InteractionManager.

**Comment by monotv** [comment]
Same behaviour here when using InteractionManager to render a placeholder for the scanner.

"react-native": "^0.30.0"
"react-native-barcodescanner": "^3.1.1"

**Comment by h2oiswater** [comment]
When I changed the camera view not full screen, this bug never show again.

This is not perfect but useful method.

**Comment by someok** [comment]
use `marginHorizontal: 1` fix the black screen problem.

```
<BarcodeScanner
                        ref={view => this.scanner = view}
                        onBarCodeRead={this._onBarCodeRead}
                        style={styles.scanner}
                    />
```

```
scanner: {
        flex: 1,

        // 上下留个边， 否则在小米下返回的时候会出现底部黑边
        marginHorizontal: 1,
    }
```

**Comment by michalkow** [comment]
@someok Your solution works for me. I have no idea how you figured that out, but kudos to you sir!

**Comment by knapeto** [comment]
OMG it works!! Thanks..

**Comment by Cocoon-break** [comment]
```js
<View style={{flex:1}}>
    <BarcodeScanner
        onBarCodeRead={this._onBarCodeRead}
        style={{flex:1}}
        torchMode={'off'}
        cameraType={'back'}/>
</View> 
```
fixed width wrap a view and style={{ flex: 1}}
