### ISSUE TITLE
Camera breaks in react-native 0.30.0

### ISSUE THREAD

**Issue by kevinnguy** [ideacreation/react-native-barcodescanner#48]
Hi all, I tried running the Example project with react-native 0.30.0 and I got this screen. Not sure if this has happened before on other react-native versions.

![1](https://cloud.githubusercontent.com/assets/1483123/17573621/8778a512-5f10-11e6-9343-257aadecbf88.png)

**Comment by patmisch** [comment]
Be sure to add `<uses-permission android:name="android.permission.CAMERA"/>` to your AndroidManifest.xml file

**Comment by kevinnguy** [comment]
Thanks a lot, @patmisch !
