### ISSUE TITLE
Extremely bad performance

### ISSUE THREAD

**Issue by morigs** [ideacreation/react-native-barcodescanner#53]
When using JS FPS is always 0, and the app so slow. Any thoughts?
- Version: 3.1.1
- Android: 6.0.1
- RN: 0.32.0

**Comment by lecramfriedrich** [comment]
I think it was already discussed on Issue https://github.com/ideacreation/react-native-barcodescanner/issues/46.

My setup is:
- Version: 3.1.1
- Android: 6.0.1
- RN: 0.31.0

It was working for me first, but than i ran into the same Performance problems again.

I am using react-native-router-flux. 
The following problem appears:
- Switching through Scenes: **Scene A** -> **Scene B** -> **Barcode Scene** -> **Scene B**
- put app in background
- restore app

Now im back to 2 FPS again and Navigation pop and push is laggy as hell. I think it's somehow connected to the **onHostResume** function from **BarcodeScannerManager**

Maybe @andreaskeller has an Idea.

**Comment by morigs** [comment]
I use react native Navigator. But barcode scene is initial. I don't through Scenes or put app in background.

**Comment by andreaskeller** [comment]
I just got an Nexus 5X with Android 6.0.1 and experience the same performance problems. On my older HTC One with Android 4.4 up to 5.5 recently everything was much faster. I am looking into it.

**Comment by AlexSchwabauer** [comment]
I opened a pull request #55 which should solve the problem by using AsyncTask so the UI thread is not blocked.

**Comment by morigs** [comment]
@AlexSchwabauer i don't know java so can't review PR. But it works fine on my phone for now! :relieved:
![screenshot_20160915-214005](https://cloud.githubusercontent.com/assets/13474134/18563612/0030b962-7b91-11e6-8ac9-1f272636528f.png)

**Comment by AlexSchwabauer** [comment]
@gogamwar Great!
I still would recommend to use  InteractionManager.runAfterInteractions to mount the component only after all animations are done, since the initial startup is quite heavy. Having state.showBarcodeScanner initially set to false and then

`componentDidMount = () => {
        InteractionManager.runAfterInteractions(() => {
             this.setState({showBarcodeScanner:true})          
        });       
}`

would to the job.

**Comment by badaz** [comment]
Thanks a lot !
