### ISSUE TITLE
View is black on react native 0.18

### ISSUE THREAD

**Issue by MikeChongCan** [ideacreation/react-native-barcodescanner#6]
I followed the instructions but it not worked.

The view is black.

Here is my code: https://github.com/imWildCat/barcode-scanner-not-working

**Comment by andreaskeller** [comment]
Hi,

If you replace `AppRegistry.registerComponent('BarcodeDemo', () => BarcodeScanner);` with `AppRegistry.registerComponent('BarcodeDemo', () => BarcodeScannerExampleApp);` it should work. Let me know if that helped.

**Comment by MikeChongCan** [comment]
@andreaskeller Sorry for my carelessness! Thanks a lot!
