### ISSUE TITLE
Changing `viewFinder*` props doesn't have any effect

### ISSUE THREAD

**Issue by andreyvital** [ideacreation/react-native-barcodescanner#9]
As the title already states... I tried to set custom values for `viewFinder*` properties and none of those worked: `viewFinderDrawLaser`, `viewFinderLaserColor`, `viewFinderBorderLength`, `viewFinderBorderWidth`.

**Comment by andreaskeller** [comment]
Changes of ReactProp class in react native 0.19 introduced these issues (https://github.com/facebook/react-native/issues/5649). Please update to newest version 1.0.0 which corrects these. Could you close the issue if the problem is solved after the update? Thank you.

**Comment by andreyvital** [comment]
Sure @andreaskeller.

**Comment by andreyvital** [comment]
Well, it worked partially, @andreaskeller. `viewFinderDrawLaser` still doesn't have any effect.
