### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by s349856186** [ideacreation/react-native-barcodescanner#93]
anyone help me 
![image](https://user-images.githubusercontent.com/2498958/40815541-d9cef296-6579-11e8-8ab1-0a7d749fa206.png)

**Comment by s349856186** [comment]
Viewfinder.propTypes = {
    backgroundColor: PropTypes.string,
    borderWidth: PropTypes.number,
    borderLength: PropTypes.number,
    color: PropTypes.string,
    height: PropTypes.number,
    isLoading: PropTypes.bool,
    width: PropTypes.number,
};
ViewFinder.js error

**Comment by ZhuravlevaS** [comment]
The same problem

**Comment by KukharevV** [comment]
Same trouble
